# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/bionic64"

  config.vm.provision "file", source: "./file.txt", destination: "~/"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get install -y python3.6 python3-pip postgresql-common libpq-dev
    pip3 install psycopg2 Django
  SHELL

end
